services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: mssql
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "${MSSQL_ACCEPT_EULA}"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    platform: ${PLATFORM}
    networks:
      - mssqlnet
  
  seq:
    image: datalust/seq:${SEQ_VERSION}
    environment:
      - ACCEPT_EULA=${SEQ_ACCEPT_EULA}
      - SEQ_FIRSTRUN_NOAUTHENTICATION=${SEQ_FIRSTRUN_NOAUTHENTICATION}
      - SEQ_PASSWORD=${SEQ_PASSWORD}
    ports:
      - "${SEQ_UI_PORT}:80"
      - "${SEQ_API_PORT}:5341"
    volumes:
      - seq_data:/data
    restart: unless-stopped
    platform: ${PLATFORM}
    networks:
      - seqnet
  
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    platform: ${PLATFORM}
    networks:
      - rabbitmqnet

volumes:
  mssql_data:
  seq_data:
  rabbitmq_data:

networks:
  seqnet:
    driver: bridge
  mssqlnet:
    driver: bridge
  rabbitmqnet:
    driver: bridge